spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
  session:
    store-type: redis
    redis:
      namespace: session
      flush-mode: on-save
  spring:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

zuul:
  sensitive-headers: Set-Cookie,Authorization

logging:
  level:
    org:
      springframework: INFO

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000
